# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://user:pass@mongodb:5432/db
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_USER: user
      MONGO_PASSWORD: pass
      MONGO_DB: db